
version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: configs/Dockerfile
    environment:
      - GOOGLE_CLOUD_PROJECT=colab-maps-v2
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app/backend # Mount for live code changes
